accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views


app_name = "accounts"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
]

blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path("post/add/", views.post_add, name="post_add"),
    path("post/<int:post_id>/", views.post_detail, name="post_detail"),
    path("post/edit/<int:post_id>/", views.post_edit, name="post_edit"),
    path("post/update/<int:post_id>/", views.post_update, name="post_update"),
    path("post/delete/<int:post_id>/", views.post_delete, name="post_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("blog/", include("blog.urls")),
    path("accounts/", include("accounts.urls")),
]

urlpatterns += static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_blog/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from main import views
from django.contrib.auth import views as auth_views_index

app_name = "main"


urlpatterns = [
    path(
        "",
        auth_views_index.LoginView.as_view(template_name="main/index.html"),
        name="index_login",
    ),
    path("main/", views.main, name="main"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    nickname = models.CharField("닉네임", max_length=30, unique=True)
    profile_image = models.ImageField(
        "프로필 이미지", upload_to="accounts/proile", blank=True
    )
    bio = models.TextField("소개글", blank=True)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from accounts.models import User


class CustomUserCreationForm(UserCreationForm):
    nickname = forms.CharField(
        max_length=30, required=True, help_text="Required. 30 characters or fewer."
    )
    profile_image = forms.ImageField(required=False)
    bio = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
        model = User
        fields = (
            "username",
            "nickname",
            "profile_image",
            "bio",
            "password1",
            "password2",
        )

    def clean_nickname(self):
        nickname = self.cleaned_data.get("nickname")
        if User.objects.filter(nickname=nickname).exists():
            raise forms.ValidationError("A user with that nickname already exists.")
        return nickname

    def save(self, commit=True):
        user = super().save(commit=False)
        user.nickname = self.cleaned_data["nickname"]
        if commit:
            user.save()
        return user


User = get_user_model()


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["nickname", "profile_image", "bio"]

        widgets = {
            "nickname": forms.TextInput(attrs={"class": "form-control"}),
            "profile_image": forms.FileInput(attrs={"class": "form-control-file"}),
            "bio": forms.Textarea(attrs={"class": "form-control", "rows": 5}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = False

    def clean_nickname(self):
        nickname = self.cleaned_data.get("nickname")
        if (
            nickname
            and User.objects.filter(nickname=nickname)
            .exclude(pk=self.instance.pk)
            .exists()
        ):
            raise forms.ValidationError("This nickname is already in use.")
        return nickname


class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = False

accounts/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, login, update_session_auth_hash
from accounts.forms import ProfileForm, CustomPasswordChangeForm


from .forms import CustomUserCreationForm, ProfileForm


def logout_view(request):
    logout(request)
    return redirect("/main/")


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse("main:main"))
    else:
        form = CustomUserCreationForm()
    return render(request, "accounts/signup.html", {"form": form})


@login_required
def edit_profile(request):
    if request.method == "POST":
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user)
        password_form = CustomPasswordChangeForm(user=request.user, data=request.POST)

        if "profile_submit" in request.POST:
            if profile_form.is_valid():
                profile_form.save()
                return redirect("main:main")
        elif "password_submit" in request.POST:
            if password_form.is_valid():
                user = password_form.save()
                update_session_auth_hash(request, user)  # 비밀번호 변경 후 세션 유지
                return redirect("main:main")
    else:
        profile_form = ProfileForm(instance=request.user)
        password_form = CustomPasswordChangeForm(user=request.user)

    context = {
        "profile_form": profile_form,
        "password_form": password_form,
    }

    return render(request, "accounts/profile.html", context)

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static '/css/wrapbox.css' %}" />
<link rel="stylesheet" href="{% static '/css/view.css' %}" />
<link rel="stylesheet" href="{% static '/css/login.css' %}" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<!-- jQuery를 먼저 로드 -->
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<!-- 그 다음 Bootstrap JavaScript를 로드 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}


{% block content %}
<div class="container my-3">
    <div class="login-wrapper">
        <p class="login-title">Login</p>
        <form method="post" action="{% url 'main:index_login' %}">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="input-id">
                <input type="text" class="form-control login-input-box" name="username" id="username"
                    value="{{ form.username.value|default_if_none:'' }}" placeholder="ID">
            </div>
            <div class="input-pw">
                <input type="password" class="form-control login-input-box" name="password" id="password"
                    value="{{ form.password.value|default_if_none:'' }}" placeholder="PASSWORD">
            </div>
            <div class="btn-box">
                <button type="submit" class="btn btn-primary login-btn">LOGIN</button>
            </div>
        </form>
        <a href="{% url 'main:main'%}" class="guest-entry">Guest entry</a>
        <a href="{% url 'accounts:signup'%}" class="create-account">Create Account</a>
    </div>
</div>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static '/css/wrapbox.css' %}" />
<link rel="stylesheet" href="{% static '/css/view.css' %}" />
<link rel="stylesheet" href="{% static '/css/profile.css' %}" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<!-- jQuery를 먼저 로드 -->
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<!-- 그 다음 Bootstrap JavaScript를 로드 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}

{% block content %}
<div class="container my-3">
    <div class="profile-wrapper">
        <p class="profile-title">Edit Profile</p>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="profile-info">
                <h3>Profile Information</h3>
                <div class="form-group">
                    <label for="username" class="profile-label">Username:</label>
                    <input type="text" id="username" name="username" value="{{ user.username }}" readonly
                        class="form-control profile-input">
                </div>
                {% for field in profile_form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}" class="profile-label">{{ field.label }}:</label>
                    {{ field }}
                </div>
                {% endfor %}
                <div class="btn-box">
                    <button type="submit" name="profile_submit" class="btn btn-primary profile-btn">Save
                        Profile</button>
                </div>
            </div>
            <div class="password-change">
                <h3>Change Password</h3>
                {% for field in password_form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}" class="profile-label">{{ field.label }}:</label>
                    {{ field }}
                </div>
                {% endfor %}
                <div class="btn-box">
                    <button type="submit" name="password_submit" class="btn btn-primary profile-btn">Change
                        Password</button>
                </div>
            </div>
        </form>
        <a href="{% url 'main:main' %}" class="cancel-btn">Cancel</a>
    </div>
</div>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static '/css/wrapbox.css' %}" />
<link rel="stylesheet" href="{% static '/css/view.css' %}" />
<link rel="stylesheet" href="{% static '/css/signup.css' %}" />

{% endblock %}


{% block content %}
<div class="container my-3">
    <div class="login-wrapper">
        <p class="login-title">Create Account</p>
        <form method="post" action="{% url 'accounts:signup' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="input-id">
                <input type="text" class="form-control login-input-box" name="username" id="username"
                    value="{{ form.username.value|default_if_none:'' }}" placeholder="Username">
            </div>
            <div class="input-nickname">
                <input type="text" class="form-control login-input-box" name="nickname" id="nickname"
                    value="{{ form.nickname.value|default_if_none:'' }}" placeholder="Nickname">
            </div>
            <div class="input-pw">
                <input type="password" class="form-control login-input-box" name="password1" id="password1"
                    value="{{ form.password1.value|default_if_none:'' }}" placeholder="Password">
            </div>
            <div class="input-pw">
                <input type="password" class="form-control login-input-box" name="password2" id="password2"
                    value="{{ form.password2.value|default_if_none:'' }}" placeholder="Confirm Password">
            </div>
            <div class="input-profile-image">
                <label for="profile_image" class="form-label">Profile Image</label>
                <input type="file" class="form-control" name="profile_image" id="profile_image">
            </div>
            <div class="btn-box">
                <button type="submit" class="btn btn-primary login-btn">SIGN UP</button>
            </div>
        </form>
        <a href="{% url 'accounts:login' %}" class="create-account">Already have an account? Login</a>
        <a href="{% url 'main:main'%}" class="">Guest entry</a>
    </div>
</div>
{% endblock %}